[project]
name = "sims"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.7"
keywords = []
authors = [
  {name = "Yunfeng Lin", email = "linyunfeng@sjtu.edu.cn" }
]
maintainers = [
  {name = "Yunfeng Lin", email = "linyunfeng@sjtu.edu.cn" }
]
dependencies = [
  "pyyaml",
  "numpy<2",
]

[project.optional-dependencies]
dev = ["check-manifest"]
test = ["coverage"]

[project.urls]
"Homepage" = "https://github.com/creeperlin/sims"
"Bug Tracker" = "https://github.com/creeperlin/sims/issues"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["sims*"]

[tool.yapf]
based_on_style = "google"
column_limit = 120
